cookie: 'sessionid=eb694465577f6cd3f7c8658a3012429b;'
url: 'https://juejin.cn/'
aid: '2608'
uuid: '7519500794585974322'
check_url: 'https://api.juejin.cn/growth_api/v1/check_in'
csrf_token: '00010000000189e9ff5d216672bc64a9ae8e4275869097b9133a727bce442156d0816210200a18985b3072449d0a'
msToken: 'zp6GW5-ffeaIkDRJzjdedvaTUuiwQWuviGaDenSnNxO-SxpI1Sxu5VpXnIjIb_qZs1n2YhjEuD4pmaJd3FeI7xCdHTLuKMjAYqIHZH0jLJ-2ZI4I0pOh9hz1x8Lbsp82'
a_bogus: 'D70YDOgaMsm13XVN07Dz9cmEEj60YWREgZEN5fbfX0Ln'